import numpy as np
# 2025-08-08 :: Dicionários revisados
# =======================================================================================================================
# DEFINIR ARQUIVOS
# =======================================================================================================================

arquivos_primarios = {
     'dicgen':'depDicionarioGenerico.xlsx',
     'periodos': 'iptPeriodos.xlsx',
     'periodos_sn': 'Períodos de Otimização',
     'cadastro_produtos': 'depSKU.xlsx',
     'cadastro_produtos_sn01':'CADASTRO',
     'cadastro_produtos_sn02':'AGRUPAMENTO',
     'portos': 'depUnidadesPortuarias.xlsx',
     'df_revisao_importada':'iptComprasImportadas.xlsx',
     'df_revisao_nacional':'iptComprasNacionais.xlsx',
     'wizard_suprimento_faixa':'tmpSuprimentoFaixa.xlsx',
     'wizard_suprimento_faixa_sn01':'SUPRIMENTO_FAIXA',
     'capacidade_portos':'iptCapacidadePortuaria.xlsx',
     'capacidade_portos_sn':'iptCapacidadePortuaria',
     'cap_op_portos':'iptLeadtime.xlsx',
     'correntes':'iptUpdateCorrentes.xlsx',
     'correntes_sn': 'iptUpdateCorrentes',
     # Os nomes de tabela abaixo foram agrupados pela redução dos arquivos primários
     'cap_prod': 'iptCapOperPlantas.xlsx',
     'cap_prod_sn': 'iptCapOperPlantas',
     'cap_desc' : 'iptCapOperPlantas.xlsx',
     'cap_desc_sn' : 'iptCapOperPlantas',
     'bom':'iptListaTecnica.xlsx',
     # Unidades Armazenagem / Produtivas / Expedição
     'unidades_exp':'depUnidadesProdutivas.xlsx',
     'unidades_exp_sn': 'depUnidadesProdutivas',
     'unidades_terceiras': 'depUnidadesGerencias.xlsx',
     'template_saida' : 'tmpCapPortProdLimMaxS.csv',
     'template_entrada' : 'tmpCapDescargaLimMaxE.csv',
     'template_capacidade' : 'tmpCapacidadeArmazenagem.xlsx',
     'template_demanda' : 'tmpDemanda.xlsx',
     'template_demanda_sn01':'SPOT_DEMANDA_PRODUTO_FAIXA',
     'template_limites' : 'tmpDefinicaoLimites.csv',
     # 2025-08-06 :: Alterado por solicitação do Matheus Ribeiro
     #'template_RendEntr':'tmpReceitasEntrada.xlsx',
     #'template_RendEntr_sn01':'RENDIMENTO_ENTRADA_PROD',
     'template_RendEntr':'tmpReceitasEntrada.csv',
     # 2025-08-06 :: Alterado por solicitação do Matheus Ribeiro
     #'template_RendSaida':'tmpReceitasSaida.xlsx',
     #'template_RendSaida_sn01':'RENDIMENTO_SAIDA_PROD',
     'template_RendSaida':'tmpReceitasSaida.csv',
     'template_fretes': 'tmpFretes.xlsx',
     'template_estoques': 'tmpEstoque.xlsx',
     'template_estoques_sn': 'VOLUME_INICIAL',
     'template_corrente_produto': 'tmpCorrenteProduto.xlsx',
     'template_imp_entrada': 'tmpImpostosEntrada.csv',
     'template_imp_saida': 'tmpImpostosSaida.csv',
     'template_rec_mov': 'tmpReceitaMovimentacao.csv',
     'template_preco': 'tmpPrecoExato.xlsx',
     'template_hand_armz': 'tmpCustosHandlingArmz.xlsx',
     'template_var_armz': 'tmpCustosVariaveisArmz.xlsx',
     'template_correntes': 'tmpCorrentes.csv',
     'unidades_por':'depUnidadesPortuarias.xlsx',
     'unidades_por_sn':'depUnidadesPortuarias',
     'mercados': 'depEstruturaComercial.xlsx',
     'demanda': 'iptDemandaIrrestrita.xlsx',
     'demanda_sn': 'iptDemandaIrrestrita',
     'arq_RendEntr': 'WIZARD_RENDIMENTO_ENTRADA.xlsx',
     'arq_RendEntr_sn01': 'RENDIMENTO_ENTRADA_PROD',
     'arq_RendSaida': 'WIZARD_RENDIMENTO_SAIDA.xlsx',
     'arq_RendSaida_sn01': 'RENDIMENTO_SAIDA_PROD',
     'arq_resultados_vcm': 'Resultados.xlsx',
     'arq_resultados_vcm_sn01': 'RESULTADOS',
     'arq_tbUpdateCorrentes': 'iptUpdateCorrentes.xlsx',
     'arq_tbUpdateCorrentes_sn': 'iptUpdateCorrentes',
     'unidades_produtoras':'depUnidadesProdutivas.xlsx',
     'demanda_cmiss':'RESULTADOS_CMISS.xlsx',
     'demanda_cmiss_sn':'Layout_DEMANDA',
     'produtos_cmiss':'depSKU_CMISS.xlsx',
     'produtos_cmiss_sn01':'CADASTRO PRODUTOS VCM',
     'produtos_cmiss_sn02':'AGRUPAMENTO',
     'fretes':'iptTabelaFretes.xlsx',
     'fretes_sn': 'iptTabelaFretes',
     'localizacao': 'depGeolocalizacao.xlsx',
     'localizacao_sn': 'depGeolocalizacao',
     'custo_internalizacao': 'iptCustoInternalizacao.xlsx',
     'custo_internalizacao_sn': 'iptCustoInternalizacao',
     'estoques_iniciais': 'iptEstoque.xlsx',
     'estoques_iniciais_sn': 'iptEstoque',
     'custo_reposicao' : 'iptCustoReposicao.xlsx',
     'custo_reposicao_sn' : 'iptCustoReposicao',
     'lista_preco' : 'iptListaPreco.xlsx',
     'lista_preco_sn' : 'iptListaPreco',
     'unidades_icms': 'depAtvcBalancosFin.xlsx',
     'unidades_icms_sn': 'depAtvcBalancosFin',
     'demurrage': 'iptDemurrage.xlsx',
     'demurrage_sn': 'iptDemurrage',
     'custos_armz': 'iptCustosArmazens.xlsx',
     'custos_armz_sn': 'iptCustosArmazens',
}

tp_dado_arquivos = {
     'dicgen':{'DE':str,'PARA':str},
     'periodos':{'NUMERO':str,'PERIODO':'datetime64[ns]', 'NOME_PERIODO':str},
     'cadastro_produtos_sn01': {'PRD-VCM':str,'CODIGO_ITEM':str,'DESCRICAO':str,'TIPO_MATERIAL':str,'CATEGORIA':str},
     'cadastro_produtos_sn02': {'COD_ESPECIFICO':str,'DESCRICAO_ESPECIFICA':str,'CODIGO_AGRUPADO':str,
                                'AGRUPAMENTO':str,'TIPO_MATERIAL':str},
     'portos': {'NOME_PORTO_VCM':str,'NOME_AZ_PORTO_VCM':str,'PORTO':str,'UNIDADE':str,'CORRENTE':str},
     'portos_correntes':{'NOME_PORTO_VCM':str,'PORTO':str,'UNIDADE':str,'CORRENTE':str},
     'df_revisao_importada':{'Porto':str,'Fábrica':str,'Matéria-prima':str,'Mês Entrega':'datetime64[ns]',
                   'BALANCE (TONS)':np.float32,'Status':str,'COMPANY':str,'RAW MATERIAL COD.':str},
     'df_revisao_nacional':{'Porto':str,'Fábrica':str,'Matéria-prima':str,'Status':str,'COMPANY':str,
                            'RAW MATERIAL COD.':str,'Mês000':np.float32,'Mês001':np.float32,'Mês002':np.float32,
                            'Mês003':np.float32,'Mês004':np.float32,'Mês005':np.float32,'Mês006':np.float32,
                            'Mês007':np.float32,'Mês008':np.float32,'Mês009':np.float32,'Mês010':np.float32,
                            'Mês011':np.float32,'Mês012':np.float32},
     'wizard_suprimento_faixa':{'Unidade':str,'Produto':str,'Periodo':str,
                                'Suprimento Mínimo':str,'Suprimento Máximo':str},
     'capacidade_portos':{'PERIODO':'datetime64[ns]'},
     'cap_op_portos':{'Porto':str,'Origem':str,'Destino':str,'Variável':str},
     'correntes':{'ConjuntoCorrentes':str,'Unidade-Origem':str,'Unidade-Destino':str,'Tipo':str},
     'cap_prod': {'Unidade':str, 'Nome Unidade':str, 'Dt/Ref':'datetime64[ns]', 'Quantidade':np.float64,'Agrupador':str,'Local':str},
     'cap_desc': {'Unidade':str, 'Nome Unidade':str, 'Dt/Ref':'datetime64[ns]', 'Quantidade':np.float64,'Agrupador':str,'Local':str},
     'cap_portos': {'PERIODO':'datetime64[ns]', '__default__':np.float64},
     'unidades_exp': {'DEPOSITO':'str','PLANTA':str, 'DESCRICAO_DEPOSITO':str, 'DESCRICAO_PLANTA':str, 'TIPO_UNIDADE':'str',
                      'UNIDADE_ARMAZENAGEM_VCM':str,'UP_MISTURADORA_VCM':str,'UNIDADE_EXPEDICAO_VCM':str},
     'unidades_terceiras':{'UNIDADE PRODUTORA':str, 'UNIDADE FATURAMENTO':str, 'GERENCIA':str, 'CONSULTORIA':str},
     'unidades_por': {'NOME_PORTO_VCM':str, 'NOME_AZ_PORTO_VCM':str, 'PORTO':str, 'UNIDADE':str, 'CORRENTE':str},
     'template_saida': {'Unidade':str, 'Periodo':str, 'Limite':str, 'Ativo':str},
     'template_entrada' : {'Unidade':str, 'Periodo':str, 'Limite':str, 'Ativo':str},
     'template_capacidade' : {'Unidade':str, 'Periodo':str, 'Volume Mínimo':np.int64, 'Volume Máximo':np.int64},
     'template_rec_mov_sn': {'Origem':str, 'Destino':str, 'Corrente':str, 'Produto':str, 'Periodo':str, 'Valor':np.float32},
     'template_preco': {'Unidade':str, 'Produto':str, 'Periodo':str, 'Preço Exato':np.float64},
     'template_hand_armz': {'Unidade':str, 'Produto':str, 'Periodo':str, 'Recebimento':np.float64, 'Expedição':np.float64},
     'template_var_armz': {'Unidade':str, 'Produto':str, 'Periodo':str, 'Valor':np.float64, 'Custo Financeiro':np.float64, 'Custo Variável':np.float64},
     'mercados':{'DIRETORIA':str,'GERENCIA':str,'CONSULTORIA':str,'CENTROID':str,'UF':str,'VCM':str},
     'demanda':{'PERIODO':'datetime64[ns]','DIRETORIA':str,'GERENCIA':str,'CONSULTORIA':str,'UNIDADE PRODUTORA':str,
               'CULTURA':str,'GRUPO PRODUTO':str,'PRODUTO':str,'CODIGO PRODUTO':str,'QUANTIDADE':np.float32},
     'template_RendSaida':{'Unidade':str, 'Receita':str, 'Produto':str, 'ValorSaida':np.float64},
     'template_RendEntr':{'Unidade':str, 'Receita':str, 'Produto':str, 'ValorEntrada':np.float64},
     'arq_RendSaida':{'Unidade':str, 'Receita':str, 'Produto':str, 'ValorSaida':np.float64},
     'arq_RendEntr':{'Unidade':str, 'Receita':str, 'Produto':str, 'ValorEntrada':np.float64},
     'arq_resultados_vcm':{'Corrente-VCM':str,'Produto-VCM':str,'Período-VCM':str, 'Quantidade':np.float64,
                          'Unidade-Origem-VCM':str,'Unidade-Destino-VCM':str,'Corredor':str},
     'arq_tbUpdateCorrentes':{'ConjuntoCorrentes':str, 'Unidade-Origem':str, 'Unidade-Destino':str, 'Tipo':str},
     'template_demanda':{'Unidade':str, 'Produto':str, 'Periodo':str, 'Demanda Mínima':np.float64, 'Demanda Máxima':np.float64},
     'template_limites':{'Unidade':str, 'Nivel Detalhe':str},
     'bom':{'PLANT_CODE':str,'PRODUCTION_SITE':str,'FG_CODE':str,'FINISHED_GOOD':str,
           'RM_CODE':str,'RM_DESCRIPTION':str,'COMPONENT_QTY':np.float64,'UOM_FORMULA':str,
           'RECIPE_CODE':str,'RECIPE_VERSION':str,'PREFERENCE':str,'FORMULA_CODE':str,
           'FORMULA_VERSION':str,'COMPANY_CODE':str},
     'demanda_cmiss':{'Produto-VCM':str, 'Produto':str, 'Período':'datetime64[ns]', 'Unidade-Destino-VCM':str,
                         'DIRETORIA':str, 'Gerencia':str, 'Consultoria':str, 'Indicador 2': str,
                         'Quantidade':np.float64},
     'produtos_cmiss_sn01':{'PRD-VCM':str, 'ITEM_CODE':str, 'ITEM_DESCRIPTION':str, 'Produto':str,
                            'Processo':str, 'Unidade VCM':str},
     'fretes': {'data_inicio':'datetime64[ns]','rota':str,'Valor':np.float64},
     'localizacao': {'Unidade':str, 'Estado':str, 'Município':str},
     'custo_internalizacao': {'MODAL':str, 'Origem':str, 'Origem Rodo':str, 'Destino':str, 'Corrente VCM':str, 'Periodo':'datetime64[ns]'},
     'template_fretes': {'Origem':str, 'Destino':str, 'Corrente':str, 'Periodo':str, 'ValorVariavel':np.float64, 'ValorContainer':np.float64},
     'template_estoques': {'Unidade':str, 'Produto':str, 'Valor':np.float64},
     'estoques_iniciais': {'PRODUCTION_UNIT':str, 'INVOICING_UNIT':str ,'ITEM_CODE':str, 'SUBINVENTORY':str,
                           'LOCATOR_DESCRIPTION':str, 'ACTUAL_STOCK':str, 'UOM':str},
     'template_corrente_produto' : {'Corrente':str, 'PRD-VCM':str},
     'template_imp_entrada' : {'Unidade Destino':str, 'Unidade Origem':str, 'Corrente':str, 'Produto':str, 'Período':str,
                               'Base de Cálculo':'float64', 'ICMS-SUBST':'int64', 'ICMS-ST':'int64'},
     'template_imp_saida' : {'Unidade Destino':str, 'Unidade Origem':str, 'Corrente':str, 'Produto':str, 'Período':str,
                               'Base de Cálculo':'float64', 'ICMS-SUBST':'int64', 'ICMS-ST':'int64'},
     'custo_reposicao': {'DH_VIGOR':'datetime64[ns]', 'DH_REFERENCIA':'datetime64[ns]', 'DT_INICIAL':'datetime64[ns]', 
                         'DT_FINAL':'datetime64[ns]', 'CD_PRODUTO':str, 'DESCRICAO_ITEM':str, 'CODIGO_ORGANIZACAO':str, 
                         'CODIGO_MOEDA':str, 'PTAX_DIA_ANTERIOR':np.float64, 'CUSTO_REPOSICAO_MERCADO':np.float64},
     'lista_preco': {'DATA':'datetime64[ns]', 'DH_INICIAL':'datetime64[ns]', 'DH_FINAL':'datetime64[ns]',
                     'FILIAL':str, 'ITEM':str, 'DESCRICAO':str, 'MOEDA':str, 'PTAX':str, 'PRECO':str, 'LISTA':str}, 
     'unidades_icms' : {'UNIDADE':str, 'DESC_UNIDADE':str, 'ZERAR_ENT':'int64', 'ZERAR_SAI':'int64', 'LOCALIZACAO':str},
     'demurrage': {'Porto':str, 'Terminal':str},
     'ptax': {'Cotação (BRL/USD)': np.float64},
     'custos_armz': {'Estado':str, 'Terceiro':str, 'Armazenagem (R$/ton)':np.float64, 'Handling (R$/ton)':np.float64},
     'template_correntes':{'Unidade':str, 'Periodo':str, 'Produto':str, 'Limite':str, 'Ativo':str},
}

rename_dataframes = {
    'df_revisao_importada':{'Porto':'PORTO','Fábrica':'PLANTA','Matéria-prima':'MP','Mês Entrega':'DT_REMESSA',
                   'BALANCE (TONS)':'BALANCE_TONS','Status':'STATUS','COMPANY':'COMPANY','RAW MATERIAL COD.':'CODIGO_MP'},
    'df_revisao_nacional':{'Porto':'PORTO','Fábrica':'PLANTA','Matéria-prima':'MP','Status':'STATUS','COMPANY':'COMPANY',
                            'RAW MATERIAL COD.':'CODIGO_MP'},
    'df_periodos':{'NUMERO':'Numero','NOME_PERIODO':'Nome VCM', 'PERIODO':'Nome'},
    'df_periodos_price':{'NOME_PERIODO':'Periodo_VCM', 'PERIODO':'Nome'},
    'df_produtos':{'CODIGO_ITEM':'ITEM_CODE'},
    'df_correntes':{'ConjuntoCorrentes':'Corrente','Unidade-Origem':'Origem','Unidade-Destino':'Destino'},
    'df_valor_compra':{'ConjuntoCorrentes':'Cód. Mat. Prima','DT_INICIAL':'Data Inicial','DT_FINAL':'Data Final',
                    'CODIGO_MOEDA':'Moeda', 'CUSTO_REPOSICAO_MERCADO':'Custo Rep. Mercado',
                    'CODIGO_ORGANIZACAO':'Desc. Empresa', 'PTAX_DIA_ANTERIOR':'Ptax Dia Anterior'},
     'df_valor_venda':{'ITEM':'Código do Produto','PRECO':'Preço','PTAX':'Ptax USD','DH_INICIAL':'Data Inicio',
                   'DH_FINAL':'Data fim','MOEDA':'Moeda','LISTA':'Nome da Lista'},
     'unidades_icms' : {'UNIDADE':'Unidades', 'DESC_UNIDADE':'Desc. Empresa', 'ZERAR_ENT':'Zerar entrada', 'ZERAR_SAI':'Zerar saída', 'LOCALIZACAO':'Localização'},
     'df_periodos_tax':{'NUMERO':'Número','NOME_PERIODO':'Periodo_VCM'},
     'df_pontos_venda':{'UNIDADE':'Origem','DESC_UNIDADE':'Origem EC'},
}